theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
logo: images/ThinkMachine_logo_fenix.svg
title: Think Machine
description: Fading Suns character sheet generator based on Java. 
author: 
  name: Jorge Hortelano
  email: softwaremagico@gmail.com

image:
  path: images/ThinkMachine_logo_fenix.png
